apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-opensearch
  namespace: opensearch
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-csi  # aksì˜ SC 
  resources:
    requests:
      storage: 10Gi
